name: Build and Deploy via Self-Hosted Runner

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<account_id>:role/GitHubRunnerECRPushRole
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: my-service
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Package Helm chart
      run: |
        helm lint ./helm/my-service
        helm package ./helm/my-service --destination ./helm-packaged

    - name: Push Helm chart to Gitea
      env:
        GITEA_USER: ${{ secrets.GITEA_USER }}
        GITEA_PASS: ${{ secrets.GITEA_PASS }}
        GITEA_REPO: "http://gitea.gitea.svc.cluster.local:3000/helm-charts/helm-charts.git"
      run: |
        git config --global user.name "ci-bot"
        git config --global user.email "ci@example.com"
        git clone http://$GITEA_USER:$GITEA_PASS@${GITEA_REPO#http://} chart-repo
        cp ./helm-packaged/*.tgz chart-repo/
        cd chart-repo
        git add .
        git commit -m "Add new Helm chart version"
        git push origin main
