# 1. SecretStore: connects External Secrets to AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: actions-runner-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1  # 
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---

# 2. ExternalSecret: pulls GitHub token from AWS and creates a K8s secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-auth-secret
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: github-auth-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github_token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: github-runner-token         #  AWS Secrets Manager secret name
        property: token                  # JSON property in secret

---

# 3. RunnerDeployment: uses the GitHub token from the synced secret
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: your-org/your-repo       # ✅ Replace with your target repo
      image: summerwind/actions-runner:latest
      group: default
      labels:
        - eks
        - github
      env: []
      volumeMounts: []
